print('Hello, please enter the following information:')

id_number = input('ID Number:')
first_name = input('First name:')
last_name = input('Last name:')
email_address = input('Email address:')
phone = input('Phone number:')
job_title = input('Job title')
hair_color = input('Your hair color: ')
eye_color = input('Color of your eyes:')
month_hired = input('Month of Admission:')
training = input('Did you complete the aditional training? ')

print("\nThe ID Card is:")
print("----------------------------------------")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job_title.title())
print(f"ID: {id_number}")
print()
print(email_address.lower())
print(phone)
print()
print(f"Hair: {hair_color:15} Eyes: {eye_color}")
print(f"Month: {month_hired:14} Training: {training}")
print("----------------------------------------")